# Standardized Dependabot Configuration
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Last updated: October 2025

version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "cboyd0319"
    assignees:
      - "cboyd0319"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # npm dependencies for VSCode extension
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "cboyd0319"
    assignees:
      - "cboyd0319"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Ignore major version updates for VSCode engine compatibility
    ignore:
      - dependency-name: "vscode"
        update-types: ["version-update:semver-major"]
