# CodeCov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"              # Test files (not production code)
  - "tools/*.ps1"           # CLI utility scripts (Apply-AutoFix, Create-Release, etc.)
  - "tools/*.py"            # Python utility scripts
  - "samples/**"            # Example/demo scripts
  - "vscode-extension/**"   # Separate VS Code extension project
  - "benchmarks/**"         # Benchmark data
  - "docs/**"               # Documentation
