# CodeCov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "tools/**"
  - "samples/**"
  - "vscode-extension/**"
  - "benchmarks/**"
  - "docs/**"
