# CodeCov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "tools/*.ps1"           # Ignore tool scripts but not lib/
  - "tools/Apply-*.ps1"
  - "tools/Create-*.ps1"
  - "tools/Prepare-*.ps1"
  - "tools/Restore-*.ps1"
  - "tools/Run-*.ps1"
  - "tools/Show-*.ps1"
  - "tools/Start-*.ps1"
  - "tools/analyze.py"
  - "samples/**"
  - "vscode-extension/**"
  - "benchmarks/**"
  - "docs/**"
