name: Lint GitHub Actions Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
      - '.github/actions/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  actionlint:
    name: Lint Workflows with actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Cache actionlint
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ./bin/actionlint
          key: ${{ runner.os }}-actionlint-latest
          restore-keys: |
            ${{ runner.os }}-actionlint-

      - name: Install actionlint
        run: |
          set -euo pipefail

          if [[ ! -f ./bin/actionlint ]]; then
            echo "Installing actionlint latest..."
            mkdir -p ./bin
            curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest ./bin
          else
            echo "actionlint already cached"
          fi

          ./bin/actionlint -version

      - name: Run actionlint
        id: actionlint
        run: |
          set -euo pipefail

          echo "::group::Running actionlint on workflows"
          ./bin/actionlint -color -verbose .github/workflows/*.yml
          echo "::endgroup::"

          echo "✓ All workflows passed actionlint validation" >> "$GITHUB_STEP_SUMMARY"

      - name: Check for YAML syntax errors
        run: |
          set -euo pipefail

          echo "::group::Checking YAML syntax"

          # Install yamllint via pip
          pip install --quiet yamllint

          # Run yamllint with relaxed rules
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}}}" .github/workflows/*.yml .github/actions/*/action.yml

          echo "::endgroup::"
          echo "✓ All YAML files have valid syntax" >> "$GITHUB_STEP_SUMMARY"
