name: Path Guard

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  guard:
    name: Validate File Organization
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate Markdown file placement
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          $base = "origin/${{ github.base_ref || 'main' }}"
          git fetch origin "${{ github.base_ref || 'main' }}"

          $changed = git diff --name-only "$base..." | Where-Object { $_ }
          $md_outside = $changed | Where-Object { $_ -match '\.md$' } | Where-Object { $_ -notmatch '^(docs/|README\.md$|CODE_OF_CONDUCT\.md$|CONTRIBUTING\.md$|SECURITY\.md$)' }

          if ($md_outside) {
            Write-Host "❌ Markdown files outside docs/:"
            $md_outside | ForEach-Object { Write-Host $_ }
            exit 1
          }
          Write-Host "✅ No misplaced Markdown files"

      - name: Add guard summary
        if: always()
        shell: pwsh
        run: |
          $status = if ("${{ job.status }}" -eq "success") { "✅ All files are correctly organized" } else { "❌ File organization violations detected" }
          @"
          ## 🛡️ Path Guard Validation

          $status

          - Markdown files: ✓ docs/ or root README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
          "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
