name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create release package
        run: |
          zip -r poshguard-${{ steps.version.outputs.VERSION }}.zip \
            tools/ \
            PoshGuard/ \
            README.md \
            LICENSE \
            docs/CHANGELOG.md \
            docs/SECURITY.md \
            docs/CONTRIBUTING.md
      
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: poshguard-${{ steps.version.outputs.VERSION }}.spdx.json
          output-file: poshguard-${{ steps.version.outputs.VERSION }}.spdx.json
          format: spdx-json
      
      - name: Attest artifact
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: poshguard-${{ steps.version.outputs.VERSION }}.zip
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            poshguard-${{ steps.version.outputs.VERSION }}.zip
            poshguard-${{ steps.version.outputs.VERSION }}.spdx.json
          body_path: docs/CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
